name: novabank

services:
  web:
    build: .
    environment: &app-env
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-dev-only-insecure-key}
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,web"
      DATABASE_URL: postgres://novabank:novabank@db:5432/novabank
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
      CHANNEL_LAYER_BACKEND: channels_redis.core.RedisChannelLayer
      SEED_DEMO: "1"
    volumes:
      - staticfiles:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  worker:
    build: .
    command: celery -A config worker --loglevel=info --concurrency=2
    environment: *app-env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: novabank
      POSTGRES_PASSWORD: novabank
      POSTGRES_DB: novabank
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U novabank"]
      interval: 3s
      timeout: 3s
      retries: 15
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 15
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/novabank.conf:/etc/nginx/conf.d/default.conf:ro
      - staticfiles:/var/www/staticfiles:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  pgdata:
  staticfiles:
