"""Account statement PDF generation (reportlab, in-memory)."""

import io
from datetime import datetime
from decimal import Decimal

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from banking.models import LedgerEntry


def _parse_date(value):
    if not value:
        return None
    try:
        return datetime.fromisoformat(value).date()
    except ValueError:
        return None


def build_account_statement(account, date_from=None, date_to=None) -> bytes:
    """Render a period statement for an operational account."""
    date_from = _parse_date(date_from)
    date_to = _parse_date(date_to)

    entries = (
        LedgerEntry.objects.filter(account=account, payment__isnull=False)
        .select_related("payment")
        .order_by("created_at")
    )
    if date_from:
        entries = entries.filter(created_at__date__gte=date_from)
    if date_to:
        entries = entries.filter(created_at__date__lte=date_to)

    entries = list(entries)
    opening = Decimal("0.00")
    closing = Decimal("0.00")
    opening_seen = Decimal("0.00")
    for entry in LedgerEntry.objects.filter(account=account).order_by("created_at"):
        if date_from and entry.created_at.date() < date_from:
            opening_seen += entry.amount
        closing += entry.amount
    opening = opening_seen if date_from else Decimal("0.00")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        title=f"NovaBank statement {account.iban}",
        leftMargin=2 * cm,
        rightMargin=2 * cm,
    )
    styles = getSampleStyleSheet()
    story = [
        Paragraph("NovaBank", styles["Title"]),
        Paragraph("Account statement", styles["Heading2"]),
        Spacer(1, 0.4 * cm),
    ]

    meta = [
        ["Account", account.name],
        ["IBAN", account.iban],
        ["Currency", account.currency],
        ["Period", f"{date_from or 'beginning'} – {date_to or 'today'}"],
        ["Opening balance", f"{opening:.2f} {account.currency}"],
        ["Closing balance", f"{closing:.2f} {account.currency}"],
    ]
    meta_table = Table(meta, colWidths=[5 * cm, 10 * cm])
    meta_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story += [meta_table, Spacer(1, 0.6 * cm)]

    rows = [["Date", "Reference", "Beneficiary", "Amount", "Balance"]]
    running = opening
    for entry in entries:
        running += entry.amount
        payment = entry.payment
        rows.append(
            [
                entry.created_at.strftime("%Y-%m-%d"),
                (payment.reference or "—")[:38],
                (payment.beneficiary_name or "Deposit")[:28],
                f"{entry.amount:+.2f}",
                f"{running:.2f}",
            ]
        )
    ledger_table = Table(rows, colWidths=[2.4 * cm, 5.4 * cm, 4.4 * cm, 2.4 * cm, 2.4 * cm])
    ledger_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a2b4a")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("ALIGN", (3, 0), (-1, -1), "RIGHT"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f4f6f9")]),
            ]
        )
    )
    story.append(ledger_table)
    story.append(Spacer(1, 0.4 * cm))
    story.append(
        Paragraph(
            "This statement was generated by the NovaBank demo platform. "
            "Document delivery is customer-scoped: it is only reachable by "
            "authenticated members of the owning organization.",
            styles["Italic"],
        )
    )
    doc.build(story)
    return buffer.getvalue()
