# Generated by Django 5.2.17 on 2026-09-29 22:52

import banking.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('iban', models.CharField(default=banking.models.generate_iban, max_length=34, unique=True)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('is_clearing', models.BooleanField(default=False, help_text='Internal counterpart account used to balance double entries.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('last4', models.CharField(max_length=4)),
                ('expiry_month', models.PositiveSmallIntegerField()),
                ('expiry_year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='banking.bankaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=100)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='accounts.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('payment', 'Outbound payment'), ('deposit', 'Inbound deposit')], default='payment', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3)),
                ('beneficiary_name', models.CharField(blank=True, max_length=200)),
                ('beneficiary_iban', models.CharField(blank=True, max_length=34)),
                ('reference', models.CharField(blank=True, max_length=140)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(help_text='The organizational account this movement belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='banking.bankaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.organization')),
                ('source_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_payments', to='banking.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='banking.bankaccount')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='banking.payment')),
            ],
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['organization', '-created_at'], name='banking_ban_organiz_fe18f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.CheckConstraint(condition=models.Q(('is_clearing', True), ('balance__gte', 0), _connector='OR'), name='operational_balance_non_negative'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['organization', '-created_at'], name='banking_car_organiz_b54dbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('organization', 'endpoint', 'key'), name='unique_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', '-created_at'], name='banking_pay_organiz_470355_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='banking_pay_status_caeb2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', '-created_at'], name='banking_led_account_b5750e_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['payment'], name='banking_led_payment_d31d20_idx'),
        ),
    ]
